name: Push

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install NPM dependencies
        run: npm ci --ignore-scripts

      - name: Run NPM format
        run: npm run format:check

      - name: Run NPM lint
        run: npm run lint
